INPUT_FILE_PART1 = "D:/Videos/part1_downsampled.mp4"
INPUT_FILE_PART2 = "D:/Videos/part2_downsampled.mp4"
INPUT_FILE_PART3_1 = "D:/Videos/part3/part3-1.mp4"
INPUT_FILE_PART3_2 = "D:/Videos/part3/part3-2_downsampled.mp4"
OUTPUT_FILE = "D:/Videos/to_split.mp4"
TEMPLATE_FILE = "D:/Videos/template_91_91.png"
TEMPLATE_FILE_CIRCLE_FIRE = "D:/Videos/part3/circle_fire.png"
FOURCC = 'mp4v'
THRESHOLD_COLOR_SPACE = "HSV"
THRESHOLD_LOW = 140  # used in binary frame of gray images (not sure if will be used)
THRESHOLD_HIGH = 185  # used in binary frames of gray images (not sure if will be used)
CALIBRATION_IMAGE = "D:/Videos/Test/calibration_thick.png"
NUMBER_FILTER_APPLICATION = 3
BILATERAL_FILTER_D = 5
SIGMA_SPACE = 5
SIGMA_COLOR = 100
RADIUS_TEMPLATE = 225
PART3_SWITCH_SCENE_0 = 15
TIME_LIMIT_END = 100
BYPASS_BILATERAL = True
BYPASS_SOBEL = True
BYPASS_HOUGH = True
BYPASS_JUNGLE = False
BYPASS_HOCKEY = True