INPUT_FILE_PART1 = "D:/Videos/part1_downsampled.mp4"
INPUT_FILE_PART2 = "D:/Videos/part2_downsampled.mp4"
INPUT_FILE_PART3 = "D:/Videos/part3_downsampled.mp4"
OUTPUT_FILE = "D:/Videos/test_2.mp4"
TEMPLATE_FILE = "D:/Videos/template_91_91.png"
FOURCC = 'mp4v'
THRESHOLD_COLOR_SPACE = "HSV"
THRESHOLD_LOW = 140  # used in binary frame of gray images (not sure if will be used)
THRESHOLD_HIGH = 185  # used in binary frames of gray images (not sure if will be used)
CALIBRATION_IMAGE = "D:/Videos/Test/calibration_thick.png"
NUMBER_FILTER_APPLICATION = 3
BILATERAL_FILTER_D = 5
SIGMA_SPACE = 5
SIGMA_COLOR = 100
BYPASS_BILATERAL = False
BYPASS_SOBEL = True
BYPASS_HOUGH = True